apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcatswebapp
  name: tomcatswebapp
  namespace: default
spec:
  ports:
  - nodePort: 31140
    port: 9093
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcatswebapp
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost